config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end

    resource :favorite, only: [:create, :destroy]
  end

  resources :carts, only: [:create]

  get 'favorites', to: 'favorites#index', as: :favorites
  
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    @favorited_products = current_user.favorited_products if user_signed_in?
  end

  def create
    @product = Product.find(params[:product_id])
    current_user.favorites.create(product: @product)
    redirect_back fallback_location: products_path, notice: 'Added to favorites.'
  end

  def destroy
    @product = Product.find(params[:product_id])
    favorite = current_user.favorites.find_by(product: @product)
    favorite.destroy if favorite
    redirect_back fallback_location: products_path, notice: 'Removed from favorites.'
  end

  private

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = 'You need to be registered or logged in to add favorites.'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<div class="container  mx-auto text-center">
  <div>
    <h1 class="mt-2"> My favorites</h1>
    <p class="mb-4 mt-8">
      Welcome, <span class="font-bold text-indigo-500"><%= current_user.email %></span>!
    </p>
    <div class="text-left hover:text-blue-700 mb-2">
      <%= link_to '<i class="fas fa-arrow-left"></i> Back to Gallery'.html_safe, root_path, class: 'text-black-500 hover:text-blue-700 mb-4' %>
    </div>
  </div>

  <div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
      <% @favorited_products.each do |product| %>
        <div class="border p-4 rounded shadow-md hover:brightness-75 transition:all duration:250">
          <% if product.images.attached? %>
            <%= link_to image_tag(product.images.first, class: "w-full h-40 object-cover mb-2"), product_path(product) %>
          <% end %>

          <h2 class="text-md font-semibold mt-2 h-10">
            <%= link_to product.name, product_path(product) %>
          </h2>

          <p class="text-gray-600 font-semibold text-sm mt-2">
            <%= product.artist_name %>
          </p>

          <p class="text-gray-600 mt-2">
            $<%= product.price %>
          </p>

          <div class="my-5">
            <% if current_user.favorited_products.include?(product) %>
              <%= link_to product_favorite_path(product), data: { turbo_method: :delete }, class: 'favorite-toggle' do %>
                <i class="fas fa-heart text-red-500 text-2xl hover:text-red-700 transition duration-300"></i>
              <% end %>
            <% else %>
              <%= link_to product_favorite_path(product), data: { turbo_method: :post }, class: 'favorite-toggle' do %>
                <i class="far fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>