config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end

    resource :favorite, only: [:create, :destroy]
  end

  resources :carts, only: [:create]

  get 'favorites', to: 'favorites#index', as: :favorites
  
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_rich_text :description
  has_many_attached :images
  belongs_to :category, optional: true

   # Association with favorites
   has_many :favorites, dependent: :destroy
   has_many :favorited_by, through: :favorites, source: :user

  validates :price, presence: true, numericality: { greater_than: 0 }
  validate :images_validation
  validates :material, presence: true
  validates :artist_name, presence: true, length: { minimum: 2 }
  validates :original, inclusion: { in: [true, false] }
  validates :year, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1500, less_than_or_equal_to: Date.today.year }

  private

  def images_validation
    if images.attached?
      images.each do |image|
        if !image.content_type.in?(%w(image/jpeg image/png))
          errors.add(:images, 'must be a JPEG or PNG file') if images.blank?
        end
      end
    else
      errors.add(:images, 'must be attached')
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  helper FavoritesHelper
  # GET /products or /products.json
  def index
    @products = Product.all

    @products = @products.order("#{sort_column} #{sort_direction}")
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    @favorite_count = @product.favorites.count
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        Rails.logger.debug @product.errors.full_messages  # Log error messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /products/1 or /products/1.json
  def update
    new_product_params = product_params.to_unsafe_h
    if new_product_params["images"].present? && new_product_params["images"].all?(&:blank?)
      new_product_params.delete("images")
    end
    respond_to do |format|
      if @product.update(new_product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
    params.require(:product).permit(
      :name, :price, :material, :artist_name, :original, :year, :category_id,  :description, images: []
    )
  end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : 'name'
    end

    def sort_direction
      if params[:direction] == "asc"
        "desc"
      else
        "asc"
      end
    end

    def current_direction
      params[:direction] || "asc"
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="flex space-x-4 my-5">
    <div class="w-1/2">
      <%= form.label :name, "Title" %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
    </div>
    <div class="w-1/2">
      <%= form.label :artist_name, "Author" %>
      <%= form.text_field :artist_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
    </div>
  </div>

 
  <div class="flex space-x-4 my-5">
    <div class="w-1/2">
      <%= form.label :material %>
      <%= form.text_field :material, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
    </div>
    <div class="w-1/2">
      <%= form.label :year %>
      <%= form.text_field :year, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
    </div>
  </div>


  <div class="my-5">
    <%= form.label :category_id, "Category" %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name', product.category_id), { include_blank: true }, { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" } %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>


  <div class="my-5">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>


  <div class="my-5">
    <%= form.radio_button :original, true %> Original
    <%= form.radio_button :original, false %> Print
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product do %>
  <div id="<%= dom_id product %>" class="max-w-sm  shadow rounded-lg p-2 mx-auto text-gray-700">
  <%= image_tag product.images.first, class:"w-full h-60 object-cover rounded-lg hover:brightness-75 transition:all duration:250" if product.images.any?  %>

  <p class="my-5 text-black">
    <%= product.name %>
  </p>

  <p class="my-5 text-gray-700">
    $ <%= product.price %>
  </p>

 <p class="my-5 text-gray-700 flex items-center">
  <% if current_user.present? %>
    <% if current_user.favorited_products.include?(product) %>
      <%= link_to product_favorite_path(product), data: { turbo_method: :delete }, class: 'text-red-600' do %>
        <i class="fas fa-heart text-red-500 text-2xl hover:text-red-700 transition duration-300"></i>
      <% end %>
    <% elsif product.favorites.any? %>
          <%= link_to product_favorite_path(product), data: { turbo_method: :post }, class: 'text-green-600' do %>
            <i class="fas fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
          <% end %>
    <% else %>
          <%= link_to product_favorite_path(product), data: { turbo_method: :post }, class: 'text-green-600' do %>
            <i class="far fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
          <% end %>
        <% end %>
    <% else %>
        <% if product.favorites.any? %>
          <i class="fas fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
        <% else %>
          <i class="far fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
        <% end %>
    <% end %>
      <span class="text-sm text-gray-600 ml-2"><%= product.favorites.count %></span>
</p>
</div>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing art</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this art", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to  gallery", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to  Admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-green-400 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full px-5 py-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-4 text-center">

    <div class="flex items-center space-x-3">
      <span class="text-gray-700 font-medium">Sort by</span>
      <div class="relative inline-block w-60">
      <select class="rounded-md border-gray-300 px-3 py-2 ml-2 cursor-pointer" onchange="location = this.value;">
      <option value="<%= products_path(sort: 'price', direction: 'desc') %>" <%= "selected" if params[:sort] == 'price' && params[:direction] == 'desc' %>>Price: Low to High</option>
      <option value="<%= products_path(sort: 'price', direction: 'asc') %>" <%= "selected" if params[:sort] == 'price' && params[:direction] == 'asc' %>>Price: High to Low</option>
      <option value="<%= products_path(sort: 'created_at', direction: 'asc') %>" <%= "selected" if params[:sort] == 'created_at' && params[:direction] == 'asc' %>>Fresh arrivals</option>
      <option value="<%= products_path(sort: 'created_at', direction: 'desc') %>" <%= "selected" if params[:sort] == 'created_at' && params[:direction] == 'desc' %>>Oldest finds</option>
      <option value="<%= products_path(sort: 'name', direction: 'desc') %>" <%= "selected" if params[:sort] == 'name' && params[:direction] == 'desc' %>>Name: A to Z</option>
      <option value="<%= products_path(sort: 'name', direction: 'asc') %>" <%= "selected" if params[:sort] == 'name' && params[:direction] == 'asc' %>>Name: Z to A</option>
    </select>
      </div>
    </div>
  </div>



  <%= link_to "Shop by Category", categories_path, class: "inline-block text-gray transition-transform duration-200 hover:scale-110" %>


  <div id="products" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-6 mb-8 mt-8">
    <% @products.each do |product| %>
      <div class="p-4 rounded-lg h-full flex flex-col">
        <%= render product %>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.getElementById('sort-menu').addEventListener('change', function() {
    window.location.href = this.value;
  });
</script>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full bg-gray-200/75 p-2 mt-4 rounded-lg">
  <h1 class="font-bold text-4xl mb-6 mt-6">New art</h1>
  <div class="mb-4">
  <%= render "form", product: @product %>

  <%= link_to "Back to gallery", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
   <%= link_to "Back to  Admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-green-300 inline-block font-medium" %>
  </div>
</div>

app/views/products/show.html.erb
<div class="w-full mt-6">


  <div class="w-full mt-6">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% elsif alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>
</div>

  <div class="max-w-7xl w-full mx-auto px-10 mb-2">
    <%= link_to "Artworks", products_path, class: "text-lg text-black-100 hover:text-gray-200" %>
    <%= link_to "> #{@product.category.name}", @product.category, class: "text-lg text-black-100 hover:text-gray-200" if @product.category %>
    <%= link_to "> #{@product.name}", @product, class: "text-lg text-black-100" %>
  </div>

  <div class="grid md:grid-cols-2 gap-4">
    <div class="max-w-md w-full mx-auto">
      <% if @product.images.any? %>
        <%= image_tag @product.images.first, class: "w-full h-96 object-cover" %>
        <div class="grid grid-cols-3 gap-4 mt-4">
          <% @product.images[1..].each do |image| %>
            <%= image_tag image, class: "w-full h-32 object-cover" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="max-w-xl flex flex-col gap-4">
      <h1 class="text-2xl font-bold text-indigo-900"> <%= @product.name %> </h1>
      <div class="text-gray-700">
      <span class="font-bold">Artist:</span>
      <%= @product.artist_name %>
      </div>
      <div class="text-gray-700">
      <span class="font-bold">Material:</span>
        <%= @product.material %>
         </div>
          <div class="text-gray-700">
          <%= @product.description %>
          </div>
          <div class="text-gray-700">
          <span class="font-bold">Year:</span>
          <%= @product.year %>
      </div>
      <div class="text-gray-700">
      <span class="font-bold">Available for sale:</span>
      <%= @product.original ? "Original" : "Print" %>
    </div>
    <div class="my-5 flex items-center gap-2">
    <% if user_signed_in? %>
      <% if current_user.favorited_products.include?(@product) %>
        <%= link_to product_favorite_path(@product), data: { turbo_method: :delete }, class: 'favorite-toggle' do %>
          <i class="fas fa-heart text-red-500 text-2xl hover:text-red-700 transition duration-300"></i>
        <% end %>
      <% elsif @product.favorites.any? %>
        <%= link_to product_favorite_path(@product), data: { turbo_method: :post }, class: 'favorite-toggle' do %>
          <i class="fas fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
        <% end %>
      <% else %>
        <%= link_to product_favorite_path(@product), data: { turbo_method: :post }, class: 'favorite-toggle' do %>
          <i class="far fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
        <% end %>
      <% end %>
    <% else %>
      <i class="<%= @product.favorites.any? ? 'fas' : 'far' %> fa-heart text-gray-500 text-2xl hover:text-gray-700 transition duration-300"></i>
    <% end %>
    <span class="text-sm text-gray-600 ml-2"><%= @product.favorites.count %></span>
  </div>


      <span class="bg-green-500 p-2 rounded-lg text-green-50 mr-auto"> <%= number_to_currency @product.price %> </span>
      <div class="flex justify-between gap-8">
        <%= link_to "Buy Now", product_buy_now_path(@product), class: "rounded-md font-semibold p-4 text-center text-md bg-yellow-400 hover:bg-yellow-500 w-60 mr-auto" %>

      </div>
    </div>
  </div>

  <% if current_admin %>
    <div class="w-full flex justify-center items-center mt-16 gap-4">
      <%= link_to "Edit this product", edit_product_path(@product), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Back to products", products_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
     <%= button_to "Destroy this product", @product, method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium",
    data: { turbo_method: :delete } %>
    </div>
  <% end %>
</div>