config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end

    resource :favorite, only: [:create, :destroy]
  end

  resources :carts, only: [:create]

  get 'favorites', to: 'favorites#index', as: :favorites
  
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 text-white py-4 mt-12">
  <div class="container mx-auto text-center">
    <p>&copy; <%= Date.today.year %> Oxana Michkasova. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="relative">

  <div class="absolute inset-0">
    <%= image_tag "artistic.jpg", class: "w-full h-40 object-cover" %>
  </div>

  <div class="relative z-10 flex-grow flex items-center justify-center text-center text-white">
    <h1 class="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold font-mag">Art Sphere</h1>
  </div>

  <nav class="relative z-10 bg-black shadow-md mt-6">
    <div class="container mx-auto px-6 py-4 flex flex-wrap justify-between items-center">

      <div class="flex items-center space-x-4">
        <%= image_tag("picture.png", class: "w-8 object-cover") %>
        <%= link_to 'Gallery', root_path, class: 'text-gray-100 hover:text-gray-600 font-medium' %>
        <% content_for :title, "Products" %>
      </div>

      <div class="flex items-center space-x-4 flex-wrap">
        <% if current_admin %>
          <%= link_to "Admin dashboard", admin_path, class: 'bg-green-500 text-white py-2 px-2 sm:px-4 rounded hover:bg-green-600' %>
          <%= link_to "Logout as Admin", destroy_admin_session_path, data: { turbo_method: :delete }, class: 'bg-red-400 text-white py-2 px-2 sm:px-4 rounded hover:bg-red-500' %>
        <% elsif current_user %>
          <%= link_to "My favorites", favorites_path, class: 'bg-purple-500 text-white py-2 px-2 sm:px-4 rounded hover:bg-purple-600' %>
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'bg-red-400 text-white py-2 px-2 sm:px-4 rounded hover:bg-red-500' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'bg-blue-500 text-white py-2 px-2 sm:px-4 rounded hover:bg-blue-600' %>
        <% end %>

      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>ArtSphere</title>
   <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
       <%= csp_meta_tag %>
  <%= favicon_link_tag 'picture.png', rel: 'icon', type: 'image/png' %>
   <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <%= javascript_importmap_tags %>
  <meta name="stripe-pk" content="<%= Rails.application.credentials.dig(:stripe, :pk) %>">
    <script src="https://js.stripe.com/v3/"></script>
 </head>

 <body class=" flex flex-col min-h-screen bg-gradient-to-r from-purple-300 via-indigo-200 to-purple-200">
 <%= render 'layouts/header' %>
   <main class=" flex-grow container mx-auto px-5 flex">
     <%= yield %>
   </main>
    <%= render 'layouts/footer' %>
  </body>
</html>